### ISSUE TITLE
Add Support for Fluvio Admin API

### ISSUE THREAD

**Issue by drc-infinyon** [infinyon/fluvio-client-python#257]
Add the ability to run the Fluvio admin commands.

Map rust crate admin methods https://docs.rs/fluvio/latest/fluvio/struct.FluvioAdmin.html 
- connect
- connect_with_config

Since the create, delete, list methods are generic over various object types, they should work for combinations available to the fluvio cli:

- topics (TopicSpec)
    - create
    - delete
    - list
    - list_with_params
    - watch
 - smartmodules (SmartModuleSpec)
   - create
   - delete
   - list
   - watch
   
    
- partitions
   -  list

**Comment by digikata** [comment]
Merged into #367
