### ISSUE TITLE
Diagnose python fluvio client CI test error for 0.10.14 update

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio-client-python#292]
A shift in smartmodule accumulate output is causing a CI test to fail w/ 0.10.14 update PR https://github.com/infinyon/fluvio-client-python/pull/286. Diagnose root cause and propose a fix.

https://github.com/infinyon/fluvio-client-python/actions/runs/5752971026/job/15595152136

**Comment by morenol** [comment]
I think that we should recompile the smartmodules used in the tests using the new version

**Comment by ozgrakkurt** [comment]
> I think that we should recompile the smartmodules used in the tests using the new version of fluvio_smartmodule

How can I do this? should I just update fluvio deps in the root `Cargo.toml`? It seems like they are on version 0.10.11/12

**Comment by morenol** [comment]
I see them here: https://github.com/infinyon/fluvio-client-python/tree/main/integration-tests/smartmodules-for-ci just the wasm file builds. I think that those are the smartmodules we have in the smartmodules/examples folder in the fluvio repo

**Comment by ozgrakkurt** [comment]
oh right, let me try updating them
