### ISSUE TITLE
Creating a ConsumerConfig raises a BusError

### ISSUE THREAD

**Issue by bencleary** [infinyon/fluvio-client-python#320]
**Description**
When creating a ConsumerConfig it raises a BusError and stops the rest of the application from executing.

**Example Code**

```python

from fluvio import Fluvio, Offset, ConsumerConfig, SmartModuleKind

class FluvioMessage(TypedDict):
    """Fluvio message payload."""
    mqtt_topic: str
    payload: dict


fluvio = Fluvio.connect()
consumer = fluvio.partition_consumer("mqtt", 0)
c = ConsumerConfig() # <-- raises BusError
c.smartmodule(
        path="./filter.wasm",
        kind=SmartModuleKind.Filter,
        params={"id": str("some-id")},
)
for msg in consumer.stream_with_config(Offset.end(), config):
      message: FluvioMessage = json.loads(bytearray(msg.value()).decode())
```

**Expected Behaviour**
I can consume with a smart module, and associated configuration.

**Current Behavious**
Raises BusError.

I am happy to help, just point me to where ever you think i should start looking 👍

**Comment by ajhunyady** [comment]
Hi @bencleary, thanks for reporting, we'll take a look.

**Comment by digikata** [comment]
HI Ben,  our CI tests have coverage of ConsumerConfig (actually it's in the setup of just about every integration test). When you get some time, I wonder if we could get the Os/Distro and Python version you're running this under.
