### ISSUE TITLE
add newest Python release 3.12 into CI

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio-client-python#325]
Python 3.12 was released on 2023-10-02, add it to CI build and publish targets

3.12 is currently incompatible w/ the fluvio-client-dependencies

**Comment by digikata** [comment]
pip installs from python3.12 may not install correctly without this publish update. (or may induce more complex pip builds with more dependencies).

**Comment by digikata** [comment]
Needs to be fixed for https://github.com/infinyon/fluvio-website/issues/705

**Comment by digikata** [comment]
It looks like this client dependency on the cpython crate causes an incompatiblity w/ 3.12 for the unit test suite (and possibly other areas).

**Comment by urbit-pilled** [comment]
fixed in https://github.com/infinyon/fluvio-client-python/pull/359
Symbol errors were due to flapigen being incompatible with 3.12
