### ISSUE TITLE
Rebuild fluvio-client-python on PyO3

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio-client-python#358]
The ['rust-cpython](https://github.com/dgrunwald/rust-cpython) crate that the fluvio python client is currently built upon is no longer maintained and is EOL for Python 3.11.

Rebuild the fluvio python client on top of the [PyO3](https://pyo3.rs) rust to python binding framework.  For the initial rebuild, a simple wrapping of the fluvio rust crate in order to connect, consume and produce (preferably async) would be a good start.

**Comment by digikata** [comment]
Note: we want to make sure the client will build and distribute for python 3.12 environments going forward.

**Comment by urbit-pilled** [comment]
fixed in https://github.com/infinyon/fluvio-client-python/pull/359
