### ISSUE TITLE
PyFluvioError: WatchApi version not found

### ISSUE THREAD

**Issue by MinLee0210** [infinyon/fluvio-client-python#461]
I setup `fluvio` and it worked well on CLI. However, I ran into a problem while following instruction using the `fluvio` package for Python. I  got this issue: 

```
PyFluvioError: WatchApi version not found
```

 In detail, I try example on [this](https://www.fluvio.io/docs/fluvio/apis/python/example/). It worked well with CLI, however, running on `.py` script, I ran into this: 

```
Traceback (most recent call last):
  File "****************/Challenges/Quira17/python_producer.py", line 10, in <module>
    fluvio = Fluvio.connect()
  File "***************/anaconda3/envs/octo/lib/python3.10/site-packages/fluvio/__init__.py", line 657, in connect
    return cls(_Fluvio.connect())
mymodule.PyFluvioError: WatchApi version not found

```

Please help!

**Comment by ajhunyady** [comment]
@MinLee0210 can you please update your fluvio cluster and python client?
Let us know if that fixed the problem.

**Comment by MinLee0210** [comment]
About python client, I installed the `fluvio-0.16.1` version. About the cluster, I followed instructions and tried both the `local` version and the `docker` version. Both worked well with CLI, but ran into troubles with `.py` scripts. 

May I know reasons for the problem I got? I'm curious to understand if there are any steps I can take on my end to resolve it. Besides, this is a new issue for me, and I'm eager to learn more.

**Comment by ajhunyady** [comment]
@digikata can you explain why this happened?

**Comment by MinLee0210** [comment]
To be honest, I can't. I such a newbie to this, just read and run the textbook.

Here is the code that I use to test: https://github.com/8Opt/Wipe.git

P/s: If I can do anything to lighten the problem, please tell.

**Comment by digikata** [comment]
@MinLee0210 Sorry to hear you are having trouble. we are investigating this, & need to clear some internal tests and release and updated version of the python client

**Comment by MinLee0210** [comment]
I have just tried. It worked perfectly! 

Thanks for your time and dedication!

**Comment by ajhunyady** [comment]
Fixed
